### ISSUE TITLE
Password is revealed in the connection_params when logging

### ISSUE THREAD

**Issue by rudeb0y** [PrefectHQ/prefect-snowflake#21]
I thought that by using a block that the password would not get exposed in any logs.. 

Which seems to work in part but not for the `connect_params` as shown below: 

    account='my_account' user='PREFECT' password=SecretStr('**********') database='my_database' 
    warehouse='DEVELOPING' private_key=None authenticator=None token=None schema_='my_schema' 
    role='SYSADMIN' autocommit=None connect_params={'account': 'my_account', 'user': 'PREFECT', 'password': 
    '<password_gets_exposed_here>', 'database': 'my_database', 'warehouse': 'DEVELOPING', 'schema': 'my_schema', 
    'role': 'SYSADMIN', 'application': 'Prefect_Snowflake_Collection'} _block_document_id=UUID('a0579d66-482e-41f8- 
    bbb4-f9a8158ff3bd') _block_document_name='snowflake-conn' _is_anonymous=False
    
That is to say

Given: 
   
     conn = await SnowflakeCredentials.load("snowflake-conn")
    logger.info(conn)

Any password held in the block is exposed in the `connection_params` dict.

**Comment by ahuang11** [comment]
Thanks so much for reporting this. Addressed in #22
