### ISSUE TITLE
Rename SnowflakeConnector 'schema' to 'schema_name'

### ISSUE THREAD

**Issue by serinamarie** [PrefectHQ/prefect-snowflake#32]
### Description
Might be nice to rename the `schema` arg in the SnowflakeConnector block.
```python
 snowflake_connector = SnowflakeConnector(
        database="db_name",
        warehouse="warehouse_name",
        schema="schema_name",
        credentials=snowflake_credentials
    )
```
### Current behavior
Accessing `snowflake_connector.database` works great; `snowflake_connector.schema` accesses the block class method called `schema()`. I need to use `snowflake_connector.schema_` to access the desired attribute.

### Desired behavior
Calling `snowflake_connector.snowflake_schema` or `snowflake_connector.schema_name` would be preferred.

**Comment by desertaxle** [comment]
Thanks for the issue! I agree that this is a rough edge right now for the `SnowflakeConnector` block, but renaming the `schema_` attribute would be a breaking change, so we may want to consider alternative options in the interim. @ahuang11 and I will discuss and see what our options are.
