### ISSUE TITLE
Issues deleting from or inserting rows from temp table using SnowflakeConnector

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect-snowflake#38]
Hi,

The process in which I load data from my ELT's is typically as follows- I have a DataFrame or a CSV that I want to load into a snowflake table. I execute a query to create a temporary table to stage my data. I then write my DataFrame to the temporary table and execute a query to remove duplicate rows from the temporary table.  From there, I insert the "deduplicated" temporary table into the original source table. 

I've been able to verify that the data within my DataFrames is correct. Additionally, the temporary tables are populating correctly. However, the commands to execute the deduplication and insert steps do not seem to be working as intended. Both the insert and delete row counts are returning as 0 rows, despite there being duplicate rows that should be deleted, and missing rows that should be inserted.

```
@task(retries=3)
def upload(index: Index, esc): #esc is the external sources snowflake connector
    name = index.name.lower()
    pks = index.PKs
    logger = get_run_logger()
    if index.dedup=='reg':
        df = index.df.replace(',','', regex=True)
        with esc.get_connection() as conn:
            with conn.cursor() as cur:
                cur.execute(f"use schema {esc.database}.{esc.schema_};")
                cur.execute(
                    f"""CREATE OR REPLACE
                    TEMPORARY TABLE TEMP_{name} LIKE {name};"""
                )
                logger.info(f"temp_{name} created")
                success, num_chunks, num_rows, _ = write_pandas(
                    conn=conn,
                    df=df,
                    table_name=f"TEMP_{name}",
                    database=esc.database,
                    schema=esc.schema_  # note the "_" suffix
                )
                logger.info(f"==> TEMPORARY TABLE TEMP_{name} LOADED")
                logger.info(num_rows)
                delete_keys = f"WHERE " + " AND ".join(
                    f"TEMP_{name}.%s = {name}.%s" % (pk, pk) for pk in pks
                )
                delete_command = f"""DELETE FROM TEMP_{name} USING {name}
                        {delete_keys};"""
                deletes = cur.execute(delete_command)
                logger.info(f"{deletes.rowcount} rows removed from {name}")
                
                inserts = cur.execute(
                    f"""INSERT INTO {name}
                        SELECT * FROM TEMP_{name};"""
                )
                logger.info(f"{inserts.rowcount} rows inserted into {name}")
```

**Comment by ahuang11** [comment]
Commenting on this for visibility; v0.2.2 was released with `snowflake_query_sync` which could potentially resolve this issue. 

@Bada-S said he'll provide updates once he tests v0.2.2.

**Comment by ahuang11** [comment]
I'll close this issue for now, but if you still encounter this, feel free to re-open!
