### ISSUE TITLE
Error "Do not provide both private_key and private_key_path; select one."

### ISSUE THREAD

**Issue by pahansen** [PrefectHQ/prefect-snowflake#62]
When I try to establish a Snowflake connection like described in the docs, I see an error:

"Do not provide both private_key and private_key_path; select one."

My flow setup looks roughly like this:

@flow
def snowflake_query_flow():
    snowflake_credentials = SnowflakeCredentials(
        account="account",
        user="user",
        password="password",
        role="MY_ROLE"
    )
    snowflake_connector = SnowflakeConnector(
        database="database",
        warehouse="warehouse",
        schema="schema",
        credentials=snowflake_credentials
    )
    result = snowflake_query(
        "SELECT * FROM my_table;",
        snowflake_connector
    )
    return result

snowflake_query_flow()

I'm using the latest version (0.25) which was released a couple of days ago. I saw that there were some changes made to this part.

**Comment by ahuang11** [comment]
Thanks for providing the reproducible example! Should be fixed in https://github.com/PrefectHQ/prefect-snowflake/pull/63
