### ISSUE TITLE
Multi-query sync

### ISSUE THREAD

**Issue by Bada-S** [PrefectHQ/prefect-snowflake#65]
Not a necessary addition, but could be a helpful feature. Essentially, if there are multiple snowflake queries that depend on each other and it would be beneficial to run them from the same session- for example - queries to build a temporary table, to stage a file, load into the temp table, perform some sort of transformation on the temp table, then load that table into the main table. `snowflake_query`, `snowflake_query_sync`, and `snowflake_multiquery` won't be able to do this as the first two run into the issue of closing the connection and dropping the temp table, and the multiquery will attempt to run those queries async.

**Comment by ahuang11** [comment]
I think if you try `SnowflakeConnector` it should work:
```

            from prefect_snowflake.credentials import SnowflakeCredentials
            from prefect_snowflake.database import SnowflakeConnector
            snowflake_credentials = SnowflakeCredentials(
                account="account",
                user="user",
                password="password",
            )
            snowflake_connector = SnowflakeConnector(
                database="database",
                warehouse="warehouse",
                schema="schema",
                credentials=snowflake_credentials
            )
            with snowflake_connector.get_connection() as connection:
                ...
```

https://docs.snowflake.com/en/user-guide/python-connector-example.html#using-context-manager-to-connect-and-control-transactions

**Comment by ahuang11** [comment]
Perhaps something like this should rollback create and insert:
```
            from prefect_snowflake.database import SnowflakeConnector
            with SnowflakeConnector.load("BLOCK_NAME") as conn:
                conn.execute(
                    "CREATE TABLE IF NOT EXISTS customers (name varchar, address varchar);"
                )
                conn.execute_many(
                    "INSERT INTO customers (name, address) VALUES (%(name)s, %(address)s);",
                    seq_of_parameters=[
                        {"name": "Ford", "address": "Highway 42"},
                        {"name": "Unknown", "address": "Space"},
                        {"name": "Me", "address": "Myway 88"},
                    ],
                )
                raise
                result = conn.fetch_one(
                    "SELECT * FROM customers WHERE address = %(address)s",
                    parameters={"address": "Space"}
                )
                print(result)
```

**Comment by Bada-S** [comment]
Closing issue with comment- will just use the SnowflakeConnector to accomplish this
